# Generated by Django 5.0.6 on 2024-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('watched', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
